dotenv: .env
networks:
  default: development
  kovan:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    dai_usd_price_feed: '0x777A68032a88E5A84678A77Af2CD65A7b3c0775a'
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136'
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    dai_usd_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'